name: Nilakandi

services:
  web:
    hostname: Nilakandi-web
    container_name: Nilakandi-web
    build:
      context: ..
      dockerfile: .docker/web/Dockerfile
    restart: always
    user: arjuna
    entrypoint: poetry run python manage.py entry_point
    stdin_open: true
    tty: true
    ports:
      - "21180:21180"
    volumes:
      - ../.env:/app/.env:ro
    networks:
      - nilakandi-net
    depends_on:
      - db
      - redis

  workers:
    hostname: Nilakandi-worker
    container_name: Nilakandi-worker
    build:
      context: ..
      dockerfile: .docker/web/Dockerfile
    restart: on-failure:5
    user: arjuna
    command: poetry run celery -A config.settings worker --loglevel=info
    tty: true
    volumes:
      - ../.env:/app/.env:ro
    networks:
      - nilakandi-net
    depends_on:
      - web

  db:
    hostname: Nilakandi-db
    container_name: Nilakandi-db
    image: postgres:13
    restart: always
    volumes:
      - nilakandi-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: arjuna
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: nilakandi
    ports:
      - 21132:5432
    networks:
      - nilakandi-net

  redis:
    hostname: Nilakandi-redis
    container_name: Nilakandi-redis
    image: redis:6
    restart: always
    networks:
      - nilakandi-net

networks:
  nilakandi-net:
    driver: bridge

volumes:
  nilakandi-db-data:
    driver: local
  minio-data:
    driver: local
