from config.env import env

AZURE_CLIENT_ID: str = env("AZURE_CLIENT_ID")
AZURE_CLIENT_SECRET: str = env("AZURE_CLIENT_SECRET")
AZURE_TENANT_ID: str = env("AZURE_TENANT_ID")
AZURE_SUBSCRIPTION_ID: str = env("AZURE_SUBSCRIPTION_ID")
AZURE_VAULT_URL: str = env("AZURE_VAULT_URL")
AZURE_STORAGE_ACCOUNT_NAME: str = env("AZURE_STORAGE_ACCOUNT_NAME")
