from config.env import env

AZURE_CLIENT_ID = env("AZURE_CLIENT_ID")
AZURE_CLIENT_SECRET = env("AZURE_CLIENT_SECRET")
AZURE_TENANT_ID = env("AZURE_TENANT_ID")
AZURE_SUBSCRIPTION_ID = env("AZURE_SUBSCRIPTION_ID")
AZURE_VAULT_URL: str = env("AZURE_VAULT_URL")
AZURE_STORAGE_ACCOUNT_NAME: str = env("AZURE_STORAGE_ACCOUNT_NAME", default="nilakandi")
AZURE_STORAGE_CONTAINER: str = env("AZURE_STORAGE_CONTAINER", default="nilakandi")
AZURE_REPORT_DOWNLOAD_DIR: str = env(
    "AZURE_REPORT_DOWNLOAD_DIR", default="azure-reports"
)
